name: "Dynamic matrix"

on: [ push ]

jobs:
  create-matrix:
        runs-on: ubuntu-latest
        outputs:
          matrix: ${{ steps.list-tags.outputs.matrix }}
        steps:
            - uses: actions/checkout@v3
              with: 
                fetch-depth: 0

            - name: List tags
              id: list-tags
              shell: pwsh
              run: | 
                $tags = git tag -l | Convertto-json -Compress
                echo "matrix=$tags" >> $env:GITHUB_OUTPUT

  debug:
    runs-on: ubuntu-latest
    needs: create-matrix
    env: 
      matrix: ${{needs.create-matrix.outputs.matrix}}
    steps:
      - name: echo output from previous job
        run: echo "$matrix"
  
  dynamic-matrix:
    runs-on: ubuntu-latest
    needs: create-matrix
    strategy:
      matrix:
        version: ${{fromJson(needs.create-matrix.outputs.matrix)}}
        version2: [10, 12, 13]
    steps:
      - run: echo "${{ matrix.version }} / ${{ matrix.version2 }}"
      