name: "Dynamic matrix"

on: [ push ]

jobs:
  create-matrix:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
              with: 
                fetch-depth: 0

            - name: List tags
              shell: pwsh
              run: | 
                git tag -l | Convertto-json -Compress 