name: "Dynamic matrix"

on: [ push ]

jobs:
  create-matrix:
        runs-on: ubuntu-latest
        outputs:
          matrix: ${{ steps.list-tags.outputs.matrix }}
        steps:
            - uses: actions/checkout@v3
              with: 
                fetch-depth: 0

            - name: List tags
              id: list-tags
              shell: pwsh
              run: | 
                $tags = git tag -l | Convertto-json -Compress
                "matrix=$tags" >> $env:GITHUB_OUTPUT

  debug:
    runs-on: ubuntu-latest
    needs: create-matrix
    steps:
        - name: echo output from previous job
          run: echo ${{needs.job.create-matrix.outputs.matrix}}